### ISSUE TITLE
Bug in DBE calculation

### ISSUE THREAD

**Issue by RobertArbon** [StructureGenerator/surge#10]
Hi folks, 

This is an excellent piece of work! I have found, however, a bug in the calculation of the DBE (I'm assuming it's the DBE that's the problem).  

consider `SyC2H10`, from a graph / valency point of view this is totally valid: 

```
from rdkit import Chem
Chem.MolFromSmiles('[SH5][CH2][CH3]')
```
![output](https://github.com/StructureGenerator/surge/assets/7603520/139109ba-628d-4584-9bf2-b26df686275f)

However, surge complains about this: 
```
(molgen) ➜  molecule_generation git:(main) surge -S 'SyC2H10'
>E surge : negative DBE
(molgen) ➜  molecule_generation git:(main) 
```

if we look at the formula parser: 

```
    *nv = forced = 0;
    totval = hydrogens;
    for (i = 0; i < numtypes; ++i)
    {
        j = elementtype[i];
        cnt = elementcount[i];
        *nv += cnt;
        totval += cnt * element[j].valence;
        if (element[j].valence > element[j].maxcoord)
            forced += element[j].valence - element[j].maxcoord;
    }
    forced = (forced+1) / 2;

    if ((totval & 1)) gt_abort(">E surge : impossible parity\n");
    dbe = totval / 2 - (*nv + hydrogens - 1) - forced;
```

the total valency (`totval`) should be `6 + 2*4 + 10 = 24`
number of heavy atoms (`nv`) is `3`
number of hydrogens (`hydrogens`) is `10`
`forced` _should_ be `0` because it is declared `int` and for all atoms except `Nx` the coordination number is equal to its valency (and thus the conditional part in the for loop is never entered in to)

so `dbe = 24/2 - (3+10-1) = 0`

Any idea what's going on please?

**Comment by steinbeck** [comment]
Thanks, Robert, for the report. 
Surge assumes a valence of 2 for sulfur. You can change the maximum coordination number with the -c# option but this will not lead to your desired behaviour as a coordination number > 4 is only allowed if no neighbours are H. We introduced this in accordance with our understanding of atom types in organic chemistry. Molgen, I think, shows the same behaviour. The fact that rdkit renders R-S5 does, IMHO, not make this a valid molecule.

**Comment by RobertArbon** [comment]
OK, thanks! Sorry, I must have missed this in the documentation as it's all there.  Apologies.
